service: eipfish
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  region: us-west-2
  memorySize: 128
  timeout: 60

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:AllocateAddress"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "ec2:ReleaseAddress"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: "arn:aws:s3:::${env:BUCKET_NAME}"
    - Effect: "Allow"
      Action:
        - "s3:*Object"
      Resource: "arn:aws:s3:::${env:BUCKET_NAME}/*"
package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  barramundi:
    handler: bin/handler
    environment:
      BUCKET_NAME: ${env:BUCKET_NAME}
      BUCKET_REGION: ${env:BUCKET_REGION}
      WEBHOOK_URL: ${env:WEBHOOK_URL}
      SHODAN_API_KEY: ${env:SHODAN_API_KEY}
    events:
      - schedule:
          rate: rate(3 minutes)
          enabled: true
          input:
            region: ap-southeast-2
            bucket: ${env:BUCKET_NAME}
  sturgeon:
    handler: bin/handler
    environment:
      BUCKET_NAME: ${env:BUCKET_NAME}
      BUCKET_REGION: ${env:BUCKET_REGION}
      WEBHOOK_URL: ${env:WEBHOOK_URL}
      SHODAN_API_KEY: ${env:SHODAN_API_KEY}
    events:
      - schedule:
          rate: rate(3 minutes)
          enabled: true
          input:
            region: us-west-2
            bucket: ${env:BUCKET_NAME}
  bass:
    handler: bin/handler
    environment:
      BUCKET_NAME: ${env:BUCKET_NAME}
      BUCKET_REGION: ${env:BUCKET_REGION}
      WEBHOOK_URL: ${env:WEBHOOK_URL}
      SHODAN_API_KEY: ${env:SHODAN_API_KEY}
    events:
      - schedule:
          rate: rate(3 minutes)
          enabled: true
          input:
            region: us-east-1
            bucket: ${env:BUCKET_NAME}
  cod:
    handler: bin/handler
    environment:
      BUCKET_NAME: ${env:BUCKET_NAME}
      BUCKET_REGION: ${env:BUCKET_REGION}
      WEBHOOK_URL: ${env:WEBHOOK_URL}
      SHODAN_API_KEY: ${env:SHODAN_API_KEY}
    events:
      - schedule:
          rate: rate(3 minutes)
          enabled: true
          input:
            region: eu-west-1
            bucket: ${env:BUCKET_NAME}
  flounder:
    handler: bin/handler
    environment:
      BUCKET_NAME: ${env:BUCKET_NAME}
      BUCKET_REGION: ${env:BUCKET_REGION}
      WEBHOOK_URL: ${env:WEBHOOK_URL}
      SHODAN_API_KEY: ${env:SHODAN_API_KEY}
    events:
      - schedule:
          rate: rate(3 minutes)
          enabled: true
          input:
            region: eu-west-2
            bucket: ${env:BUCKET_NAME}
